version: '3.9' # ファイルのバージョン

services:
  app: # サービス名は任意
    container_name: app
    build: ./docker/php
    # ↑ビルドコンテキストを指定 → docker buildを実行する際の現在の作業ディレクトリのこと
    # Dockerfileが置かれているディレクトリ
    volumes:
      - ${SRC_PATH}:/usr/share/nginx/html # ./srcディレクトリをappのコンテナ内/dataへマウント

  web:
    container_name: web
    image: nginx:1.22-alpine # nginxは偶数が安定ver.
    ports:
      - 8080:80 # ホスト側:コンテナ側
    volumes:
      - ${SRC_PATH}:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html

  db:
    container_name: db
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: